/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as PlaylistRouteImport } from './../routes/playlist'
import { Route as OauthCallbackRouteImport } from './../routes/oauth-callback'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as TracksTrackIdRouteImport } from './../routes/tracks.$trackId'
import { Route as PlaylistsAddRouteImport } from './../routes/playlists.add'
import { Route as PlaylistsPlaylistIdEditRouteImport } from './../routes/playlists.$playlistId.edit'
import { Route as PlaylistsPlaylistIdAddCoverRouteImport } from './../routes/playlists.$playlistId.addCover'

const PlaylistRoute = PlaylistRouteImport.update({
  id: '/playlist',
  path: '/playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksTrackIdRoute = TracksTrackIdRouteImport.update({
  id: '/tracks/$trackId',
  path: '/tracks/$trackId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsAddRoute = PlaylistsAddRouteImport.update({
  id: '/playlists/add',
  path: '/playlists/add',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsPlaylistIdEditRoute = PlaylistsPlaylistIdEditRouteImport.update({
  id: '/playlists/$playlistId/edit',
  path: '/playlists/$playlistId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsPlaylistIdAddCoverRoute =
  PlaylistsPlaylistIdAddCoverRouteImport.update({
    id: '/playlists/$playlistId/addCover',
    path: '/playlists/$playlistId/addCover',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/playlist': typeof PlaylistRoute
  '/playlists/add': typeof PlaylistsAddRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/playlists/$playlistId/addCover': typeof PlaylistsPlaylistIdAddCoverRoute
  '/playlists/$playlistId/edit': typeof PlaylistsPlaylistIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/playlist': typeof PlaylistRoute
  '/playlists/add': typeof PlaylistsAddRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/playlists/$playlistId/addCover': typeof PlaylistsPlaylistIdAddCoverRoute
  '/playlists/$playlistId/edit': typeof PlaylistsPlaylistIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/playlist': typeof PlaylistRoute
  '/playlists/add': typeof PlaylistsAddRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/playlists/$playlistId/addCover': typeof PlaylistsPlaylistIdAddCoverRoute
  '/playlists/$playlistId/edit': typeof PlaylistsPlaylistIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/oauth-callback'
    | '/playlist'
    | '/playlists/add'
    | '/tracks/$trackId'
    | '/playlists/$playlistId/addCover'
    | '/playlists/$playlistId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/oauth-callback'
    | '/playlist'
    | '/playlists/add'
    | '/tracks/$trackId'
    | '/playlists/$playlistId/addCover'
    | '/playlists/$playlistId/edit'
  id:
    | '__root__'
    | '/'
    | '/oauth-callback'
    | '/playlist'
    | '/playlists/add'
    | '/tracks/$trackId'
    | '/playlists/$playlistId/addCover'
    | '/playlists/$playlistId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  PlaylistRoute: typeof PlaylistRoute
  PlaylistsAddRoute: typeof PlaylistsAddRoute
  TracksTrackIdRoute: typeof TracksTrackIdRoute
  PlaylistsPlaylistIdAddCoverRoute: typeof PlaylistsPlaylistIdAddCoverRoute
  PlaylistsPlaylistIdEditRoute: typeof PlaylistsPlaylistIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playlist': {
      id: '/playlist'
      path: '/playlist'
      fullPath: '/playlist'
      preLoaderRoute: typeof PlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-callback': {
      id: '/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/$trackId': {
      id: '/tracks/$trackId'
      path: '/tracks/$trackId'
      fullPath: '/tracks/$trackId'
      preLoaderRoute: typeof TracksTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/add': {
      id: '/playlists/add'
      path: '/playlists/add'
      fullPath: '/playlists/add'
      preLoaderRoute: typeof PlaylistsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$playlistId/edit': {
      id: '/playlists/$playlistId/edit'
      path: '/playlists/$playlistId/edit'
      fullPath: '/playlists/$playlistId/edit'
      preLoaderRoute: typeof PlaylistsPlaylistIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$playlistId/addCover': {
      id: '/playlists/$playlistId/addCover'
      path: '/playlists/$playlistId/addCover'
      fullPath: '/playlists/$playlistId/addCover'
      preLoaderRoute: typeof PlaylistsPlaylistIdAddCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  PlaylistRoute: PlaylistRoute,
  PlaylistsAddRoute: PlaylistsAddRoute,
  TracksTrackIdRoute: TracksTrackIdRoute,
  PlaylistsPlaylistIdAddCoverRoute: PlaylistsPlaylistIdAddCoverRoute,
  PlaylistsPlaylistIdEditRoute: PlaylistsPlaylistIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
